FROM python:3.11-slim

WORKDIR /app

# sadece api requirements
COPY apps/api/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# sadece api kodu
COPY apps/api /app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]